# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mensagem.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/mensagem.proto\x12\ntoken_ring\"\x0e\n\x0cTokenRequest\"\x0f\n\rTokenResponse2O\n\tTokenRing\x12\x42\n\tPassToken\x12\x18.token_ring.TokenRequest\x1a\x19.token_ring.TokenResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.mensagem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENREQUEST']._serialized_start=36
  _globals['_TOKENREQUEST']._serialized_end=50
  _globals['_TOKENRESPONSE']._serialized_start=52
  _globals['_TOKENRESPONSE']._serialized_end=67
  _globals['_TOKENRING']._serialized_start=69
  _globals['_TOKENRING']._serialized_end=148
# @@protoc_insertion_point(module_scope)
