# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import mensagem_pb2 as proto_dot_mensagem__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/mensagem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class BullyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Election = channel.unary_unary(
                '/bully.Bully/Election',
                request_serializer=proto_dot_mensagem__pb2.IdRequest.SerializeToString,
                response_deserializer=proto_dot_mensagem__pb2.IdResponse.FromString,
                _registered_method=True)
        self.Alive = channel.unary_unary(
                '/bully.Bully/Alive',
                request_serializer=proto_dot_mensagem__pb2.IdRequest.SerializeToString,
                response_deserializer=proto_dot_mensagem__pb2.IdResponse.FromString,
                _registered_method=True)
        self.Victory = channel.unary_unary(
                '/bully.Bully/Victory',
                request_serializer=proto_dot_mensagem__pb2.IdRequest.SerializeToString,
                response_deserializer=proto_dot_mensagem__pb2.IdResponse.FromString,
                _registered_method=True)
        self.Ok = channel.unary_unary(
                '/bully.Bully/Ok',
                request_serializer=proto_dot_mensagem__pb2.IdRequest.SerializeToString,
                response_deserializer=proto_dot_mensagem__pb2.IdResponse.FromString,
                _registered_method=True)


class BullyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Election(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Alive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Victory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ok(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BullyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Election': grpc.unary_unary_rpc_method_handler(
                    servicer.Election,
                    request_deserializer=proto_dot_mensagem__pb2.IdRequest.FromString,
                    response_serializer=proto_dot_mensagem__pb2.IdResponse.SerializeToString,
            ),
            'Alive': grpc.unary_unary_rpc_method_handler(
                    servicer.Alive,
                    request_deserializer=proto_dot_mensagem__pb2.IdRequest.FromString,
                    response_serializer=proto_dot_mensagem__pb2.IdResponse.SerializeToString,
            ),
            'Victory': grpc.unary_unary_rpc_method_handler(
                    servicer.Victory,
                    request_deserializer=proto_dot_mensagem__pb2.IdRequest.FromString,
                    response_serializer=proto_dot_mensagem__pb2.IdResponse.SerializeToString,
            ),
            'Ok': grpc.unary_unary_rpc_method_handler(
                    servicer.Ok,
                    request_deserializer=proto_dot_mensagem__pb2.IdRequest.FromString,
                    response_serializer=proto_dot_mensagem__pb2.IdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bully.Bully', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bully.Bully', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bully(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Election(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bully.Bully/Election',
            proto_dot_mensagem__pb2.IdRequest.SerializeToString,
            proto_dot_mensagem__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Alive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bully.Bully/Alive',
            proto_dot_mensagem__pb2.IdRequest.SerializeToString,
            proto_dot_mensagem__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Victory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bully.Bully/Victory',
            proto_dot_mensagem__pb2.IdRequest.SerializeToString,
            proto_dot_mensagem__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ok(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bully.Bully/Ok',
            proto_dot_mensagem__pb2.IdRequest.SerializeToString,
            proto_dot_mensagem__pb2.IdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
