# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/mensagem.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/mensagem.proto\x12\x05\x62ully\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x0c\n\nIdResponse2\xc9\x01\n\x05\x42ully\x12\x31\n\x08\x45lection\x12\x10.bully.IdRequest\x1a\x11.bully.IdResponse\"\x00\x12.\n\x05\x41live\x12\x10.bully.IdRequest\x1a\x11.bully.IdResponse\"\x00\x12\x30\n\x07Victory\x12\x10.bully.IdRequest\x1a\x11.bully.IdResponse\"\x00\x12+\n\x02Ok\x12\x10.bully.IdRequest\x1a\x11.bully.IdResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.mensagem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDREQUEST']._serialized_start=31
  _globals['_IDREQUEST']._serialized_end=54
  _globals['_IDRESPONSE']._serialized_start=56
  _globals['_IDRESPONSE']._serialized_end=68
  _globals['_BULLY']._serialized_start=71
  _globals['_BULLY']._serialized_end=272
# @@protoc_insertion_point(module_scope)
